media:
  input: img
  output: /img
components:
  hero: # 'hero' is the component name/key
    label: About Section
    type: object
    fields:
      - name: headline
        label: Headline
        type: text
        required: true
      - name: body
        label: Body
        type: rich-text
content:
  - name: posts
    label: Posts
    type: collection
    path: content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: draft, label: Draft, type: boolean }
      - { name: featured, label: Featured, type: boolean, default: false }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }
      - {  name: cover, label: Cover Image, type: image}
  - name: events
    label: Events
    type: collection
    path: content/event
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }
      - {  name: cover, label: Cover Image, type: image}
  - name: about
    label: About page
    type: file
    path: content/about/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Key, type: string }
          - { name: order, label: Order, type: number }
          - { name: body, label: Body, type: rich-text }
  - name: metadata
    label: Metadata
    type: file
    path: _data/metadata.js
    format: code

